// src/data/users.ts

export interface User {
  id: number;
  fullName: string;
  staffId: string;
  username: string;
  department: string;
  position: string;
  role: string;
  status: boolean;
}

export const usersData: User[] = [
  {
    id: 1,
    fullName: "John Doe",
    staffId: "S001",
    username: "johndoe",
    department: "HR",
    position: "Manager",
    role: "Admin",
    status: true,
  },
  {
    id: 2,
    fullName: "Jane Smith",
    staffId: "S002",
    username: "janesmith",
    department: "IT",
    position: "Developer",
    role: "User",
    status: false,
  },
  {
    id: 3,
    fullName: "Alice Johnson",
    staffId: "S003",
    username: "alicejohnson",
    department: "Finance",
    position: "Analyst",
    role: "User",
    status: true,
  },
  {
    id: 4,
    fullName: "Bob Brown",
    staffId: "S004",
    username: "bobbrown",
    department: "IT",
    position: "DevOps",
    role: "User",
    status: true,
  },
  {
    id: 5,
    fullName: "Charlie Davis",
    staffId: "S005",
    username: "charliedavis",
    department: "Marketing",
    position: "Executive",
    role: "User",
    status: true,
  },
  {
    id: 6,
    fullName: "Daniel Evans",
    staffId: "S006",
    username: "danielevans",
    department: "HR",
    position: "Recruiter",
    role: "User",
    status: false,
  },
  {
    id: 7,
    fullName: "Eva Green",
    staffId: "S007",
    username: "evagreen",
    department: "IT",
    position: "Software Engineer",
    role: "User",
    status: true,
  },
  {
    id: 8,
    fullName: "Frank Harris",
    staffId: "S008",
    username: "frankharris",
    department: "Finance",
    position: "Accountant",
    role: "User",
    status: false,
  },
  {
    id: 9,
    fullName: "Grace Lee",
    staffId: "S009",
    username: "gracelee",
    department: "Sales",
    position: "Sales Manager",
    role: "Admin",
    status: true,
  },
  {
    id: 10,
    fullName: "Henry Miller",
    staffId: "S010",
    username: "henrymiller",
    department: "Operations",
    position: "Manager",
    role: "Admin",
    status: false,
  },
  {
    id: 11,
    fullName: "Isabella Moore",
    staffId: "S011",
    username: "isabellamoore",
    department: "IT",
    position: "Data Scientist",
    role: "User",
    status: true,
  },
  {
    id: 12,
    fullName: "Jack Wilson",
    staffId: "S012",
    username: "jackwilson",
    department: "HR",
    position: "HR Assistant",
    role: "User",
    status: true,
  },
  {
    id: 13,
    fullName: "Kathy Taylor",
    staffId: "S013",
    username: "kathytaylor",
    department: "Finance",
    position: "Treasurer",
    role: "User",
    status: false,
  },
  {
    id: 14,
    fullName: "Liam Thompson",
    staffId: "S014",
    username: "liamthompson",
    department: "IT",
    position: "Web Developer",
    role: "User",
    status: true,
  },
  {
    id: 15,
    fullName: "Mia Martinez",
    staffId: "S015",
    username: "miamartinez",
    department: "Marketing",
    position: "Marketing Manager",
    role: "Admin",
    status: true,
  },
  {
    id: 16,
    fullName: "Noah White",
    staffId: "S016",
    username: "noahwhite",
    department: "Operations",
    position: "Operations Assistant",
    role: "User",
    status: false,
  },
  {
    id: 17,
    fullName: "Olivia Harris",
    staffId: "S017",
    username: "oliviaharris",
    department: "Sales",
    position: "Sales Executive",
    role: "User",
    status: true,
  },
  {
    id: 18,
    fullName: "Paul Walker",
    staffId: "S018",
    username: "paulwalker",
    department: "Finance",
    position: "Financial Analyst",
    role: "User",
    status: false,
  },
  {
    id: 19,
    fullName: "Quinn Young",
    staffId: "S019",
    username: "quinnyoung",
    department: "IT",
    position: "IT Support",
    role: "User",
    status: true,
  },
  {
    id: 20,
    fullName: "Riley King",
    staffId: "S020",
    username: "rileyking",
    department: "HR",
    position: "HR Manager",
    role: "Admin",
    status: true,
  },
  {
    id: 21,
    fullName: "Sophie Adams",
    staffId: "S021",
    username: "sophieadams",
    department: "HR",
    position: "Recruiter",
    role: "User",
    status: true,
  },
  {
    id: 22,
    fullName: "Tom Johnson",
    staffId: "S022",
    username: "tomjohnson",
    department: "IT",
    position: "Network Engineer",
    role: "User",
    status: false,
  },
  {
    id: 23,
    fullName: "Uma Thurman",
    staffId: "S023",
    username: "umathurman",
    department: "Finance",
    position: "Finance Manager",
    role: "Admin",
    status: true,
  },
  {
    id: 24,
    fullName: "Vera Wang",
    staffId: "S024",
    username: "verawang",
    department: "Marketing",
    position: "Marketing Executive",
    role: "User",
    status: true,
  },
  {
    id: 25,
    fullName: "Will Smith",
    staffId: "S025",
    username: "willsmith",
    department: "IT",
    position: "Project Manager",
    role: "Admin",
    status: false,
  },
  {
    id: 26,
    fullName: "Xena Warrior",
    staffId: "S026",
    username: "xenawarrior",
    department: "Sales",
    position: "Sales Executive",
    role: "User",
    status: true,
  },
  {
    id: 27,
    fullName: "Yasmin Lee",
    staffId: "S027",
    username: "yasminlee",
    department: "HR",
    position: "HR Coordinator",
    role: "User",
    status: true,
  },
  {
    id: 28,
    fullName: "Zane Grey",
    staffId: "S028",
    username: "zanegrey",
    department: "Finance",
    position: "Senior Analyst",
    role: "Admin",
    status: false,
  },
  {
    id: 29,
    fullName: "Abby Sciuto",
    staffId: "S029",
    username: "abbysciuto",
    department: "IT",
    position: "Security Analyst",
    role: "User",
    status: true,
  },
  {
    id: 30,
    fullName: "Bobby Singer",
    staffId: "S030",
    username: "bobbysinger",
    department: "Marketing",
    position: "Digital Marketer",
    role: "User",
    status: true,
  },
  {
    id: 31,
    fullName: "Catherine O'Hara",
    staffId: "S031",
    username: "catherineohara",
    department: "Operations",
    position: "Operations Manager",
    role: "Admin",
    status: true,
  },
  {
    id: 32,
    fullName: "David Beckham",
    staffId: "S032",
    username: "davidbeckham",
    department: "Sales",
    position: "Regional Manager",
    role: "User",
    status: false,
  },
  {
    id: 33,
    fullName: "Eva Mendes",
    staffId: "S033",
    username: "evamendes",
    department: "HR",
    position: "Recruitment Specialist",
    role: "User",
    status: true,
  },
  {
    id: 34,
    fullName: "Fiona Apple",
    staffId: "S034",
    username: "fionaapple",
    department: "IT",
    position: "Database Administrator",
    role: "Admin",
    status: true,
  },
  {
    id: 35,
    fullName: "Gordon Ramsay",
    staffId: "S035",
    username: "gordonramsay",
    department: "Finance",
    position: "Financial Controller",
    role: "User",
    status: true,
  },
  {
    id: 36,
    fullName: "Hannah Montana",
    staffId: "S036",
    username: "hannahmontana",
    department: "Marketing",
    position: "Content Writer",
    role: "User",
    status: false,
  },
  {
    id: 37,
    fullName: "Ian Malcolm",
    staffId: "S037",
    username: "ianmalcolm",
    department: "Operations",
    position: "Operations Supervisor",
    role: "User",
    status: true,
  },
  {
    id: 38,
    fullName: "Jenna Ortega",
    staffId: "S038",
    username: "jennaortega",
    department: "IT",
    position: "UX/UI Designer",
    role: "Admin",
    status: false,
  },
  {
    id: 39,
    fullName: "Kurt Cobain",
    staffId: "S039",
    username: "kurtcobain",
    department: "HR",
    position: "Training Specialist",
    role: "User",
    status: true,
  },
  {
    id: 40,
    fullName: "Linda Hamilton",
    staffId: "S040",
    username: "lindahamilton",
    department: "Sales",
    position: "Sales Associate",
    role: "User",
    status: true,
  },
];

// src/app/unauthorized-records/recordsData.ts

export interface Record {
  srNumber: string;
  reconcileDate: string;
  branch: string;
  txnType: string;
  cashCustodian: string;
  checker: string;
  approver: string;
  status: string;
}

export const recordsData: Record[] = [
  {
    srNumber: "2024080001",
    reconcileDate: "8/31/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 1",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080002",
    reconcileDate: "8/31/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 2",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080003",
    reconcileDate: "9/1/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 3",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080004",
    reconcileDate: "9/2/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 4",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080005",
    reconcileDate: "9/3/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 5",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080006",
    reconcileDate: "9/4/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 6",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080007",
    reconcileDate: "9/5/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 7",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080008",
    reconcileDate: "9/6/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 8",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080009",
    reconcileDate: "9/7/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 9",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080010",
    reconcileDate: "9/8/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 10",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080011",
    reconcileDate: "9/9/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 11",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080012",
    reconcileDate: "9/10/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 12",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080013",
    reconcileDate: "9/11/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 13",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080014",
    reconcileDate: "9/12/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 14",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080015",
    reconcileDate: "9/13/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 15",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080016",
    reconcileDate: "9/14/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 16",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080017",
    reconcileDate: "9/15/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 17",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080018",
    reconcileDate: "9/16/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 18",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080019",
    reconcileDate: "9/17/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 19",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080020",
    reconcileDate: "9/18/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 20",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080021",
    reconcileDate: "9/19/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 21",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080022",
    reconcileDate: "9/20/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 22",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080023",
    reconcileDate: "9/21/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 23",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080024",
    reconcileDate: "9/22/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 24",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080025",
    reconcileDate: "9/23/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 25",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080026",
    reconcileDate: "9/24/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 26",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080027",
    reconcileDate: "9/25/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 27",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080028",
    reconcileDate: "9/26/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 28",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080029",
    reconcileDate: "9/27/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 29",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080030",
    reconcileDate: "9/28/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 30",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080031",
    reconcileDate: "9/29/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 31",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080032",
    reconcileDate: "9/30/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 32",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080033",
    reconcileDate: "10/1/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 33",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080034",
    reconcileDate: "10/2/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 34",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080035",
    reconcileDate: "10/3/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 35",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080036",
    reconcileDate: "10/4/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 36",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080037",
    reconcileDate: "10/5/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 37",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080038",
    reconcileDate: "10/6/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 38",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  {
    srNumber: "2024080039",
    reconcileDate: "10/7/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 39",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Pending",
  },
  {
    srNumber: "2024080040",
    reconcileDate: "10/8/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 40",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Processing",
  },
  {
    srNumber: "2024080041",
    reconcileDate: "10/9/2024",
    branch: "ASL",
    txnType: "Unauthorized Type 41",
    cashCustodian: "Ouk Makara",
    checker: "Mao Kimhong",
    approver: "Hong Sokviet",
    status: "Completed",
  },
  // Add more records as needed
];
